// `.env.json` is generated by the `npm run build` command
import * as env from './.env.json';

import { PMS_ENV } from '../assets/js/env';


export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: PMS_ENV.SERVER_URL,
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
